[package]
name = "AptosSwapLP"
version = "0.0.1"

[dependencies]
AptosSwap = { git = "https://github.com/pontem-network/aptos-swap.git", rev = "f18a30c23e49aab7fb33aa6cbdda335c96d332b9" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a615536bdb8a8dedb7ec029ddfbf12b80b64f979"
subdir = "aptos-move/framework/aptos-framework/"

[addresses]
Account = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
