[package]
name = "LiquidswapLP"
version = "0.4.9"
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "f18cc2cac521b2a2eae5a5f08f1b787f61a2279d"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
liquidswap_lp = "0x19f6b26011f2f4050b895de44bf93d7c25f54117ac2f8736287257cc20e351bb"
