[package]
name = "AptosSwapLP"
version = "0.1.0"

[dependencies]
AptosSwap = { git = "https://github.com/pontem-network/aptos-swap.git", rev = "master" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "bb3a847c6ae8967661826775cd026f6fdb2abf0c"
subdir = "aptos-move/framework/aptos-framework/"

[addresses]
Account = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
