[package]
name = "LiquidswapLP"
version = "0.4.12"
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "971c160079263a8d3e1d2503a570b01ecaaf10ba"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
liquidswap_lp = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
