[package]
name = "LiquidswapLP"
version = "0.4.2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "908aff867fcc1e1b12f058d474329097ab96f14b"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
liquidswap_lp = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
