[package]
name = "LiquidswapLP"
version = "0.3.0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
liquidswap_lp = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
